// tslint:disable
/**
 * API for the Short Sale Register
 *   This API delivers information about public shorting of instruments that have Finanstilsynet as relevant competent authority (RCA).    ## Notice about historical data  We only deliver information about shortings that were active within the past two years.  
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: ssr@finanstilsynet.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    UnderlyingShortPosition,
} from './';

/**
 *   Describes a short event. Such an event is triggered when there is a change in the public shorting of the instrument.    Examples: a new position holder shorts this instrument, or an existing position holder updates its short on the instrument.
 * @export
 * @interface AggregatedShortEvent
 */
export interface AggregatedShortEvent {
    /**
     * The date of the short event
     * @type {string}
     * @memberof AggregatedShortEvent
     */
    date?: string;
    /**
     * Aggregated (total) short percentage
     * @type {number}
     * @memberof AggregatedShortEvent
     */
    shortPercent?: number;
    /**
     * Aggregated (total) number of shorted shares
     * @type {number}
     * @memberof AggregatedShortEvent
     */
    shares?: number;
    /**
     * List of all the active public positions on the instrument at the given date. Together they make up this aggregated short event. See [UnderlyingShortPosition](#section/UnderlyingShortPosition)
     * @type {Array<UnderlyingShortPosition>}
     * @memberof AggregatedShortEvent
     */
    activePositions?: Array<UnderlyingShortPosition>;
}
