// tslint:disable
/**
 * API for the Short Sale Register
 *   This API delivers information about public shorting of instruments that have Finanstilsynet as relevant competent authority (RCA).    ## Notice about historical data  We only deliver information about shortings that were active within the past two years.  
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: ssr@finanstilsynet.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes an individual short position.
 * @export
 * @interface UnderlyingShortPosition
 */
export interface UnderlyingShortPosition {
    /**
     * The shorting date for this position
     * @type {string}
     * @memberof UnderlyingShortPosition
     */
    date?: string;
    /**
     * The percentage of the total shares of the instrument shorted in this position
     * @type {number}
     * @memberof UnderlyingShortPosition
     */
    shortPercent?: number;
    /**
     * The number of shares shorted in this position
     * @type {number}
     * @memberof UnderlyingShortPosition
     */
    shares?: number;
    /**
     * The holder of this short position
     * @type {string}
     * @memberof UnderlyingShortPosition
     */
    positionHolder?: string;
}
